#ifndef __JCC_H__
#define __JCC_H__
//jo
make_helper(jo_r_b);
//jno
make_helper(jno_r_b);
//jb
make_helper(jb_r_b);
//jae
make_helper(jae_r_b);
//je
make_helper(je_r_b);
//jne
make_helper(jne_r_b);
//jbe
make_helper(jbe_r_b);
//ja
make_helper(ja_r_b);
//js
make_helper(js_r_b);
//jns
make_helper(jns_r_b);
//jp
make_helper(jp_r_b);
//jnp
make_helper(jnp_r_b);
//jl
make_helper(jl_r_b);
//jge
make_helper(jge_r_b);
//jle
make_helper(jle_r_b);
//jg
make_helper(jg_r_b);
//jmp
make_helper(jmp_r_b);
//jcxz
make_helper(jcxz_r_b);
//setcc
make_helper(seto_rm_b);
make_helper(setno_rm_b);
make_helper(setb_rm_b);
make_helper(setae_rm_b);
make_helper(sete_rm_b);
make_helper(setne_rm_b);
make_helper(setbe_rm_b);
make_helper(seta_rm_b);
make_helper(sets_rm_b);
make_helper(setns_rm_b);
make_helper(setp_rm_b);
make_helper(setnp_rm_b);
make_helper(setl_rm_b);
make_helper(setge_rm_b);
make_helper(setle_rm_b);
make_helper(setg_rm_b);

//jo
make_helper(jo_r_v);
//jno
make_helper(jno_r_v);
//jb
make_helper(jb_r_v);
//jae
make_helper(jae_r_v);
//je
make_helper(je_r_v);
//jne
make_helper(jne_r_v);
//jbe
make_helper(jbe_r_v);
//ja
make_helper(ja_r_v);
//js
make_helper(js_r_v);
//jns
make_helper(jns_r_v);
//jp
make_helper(jp_r_v);
//jnp
make_helper(jnp_r_v);
//jl
make_helper(jl_r_v);
//jge
make_helper(jge_r_v);
//jle
make_helper(jle_r_v);
//jg
make_helper(jg_r_v);
//jmp
make_helper(jmp_r_v);
make_helper(jmp_rm_v);
make_helper(ljmp_v);
//setcc
make_helper(seto_rm_v);
make_helper(setno_rm_v);
make_helper(setb_rm_v);
make_helper(setae_rm_v);
make_helper(sete_rm_v);
make_helper(setne_rm_v);
make_helper(setbe_rm_v);
make_helper(seta_rm_v);
make_helper(sets_rm_v);
make_helper(setns_rm_v);
make_helper(setp_rm_v);
make_helper(setnp_rm_v);
make_helper(setl_rm_v);
make_helper(setge_rm_v);
make_helper(setle_rm_v);
make_helper(setg_rm_v);
#endif
