#ifndef __add_H__
#define __add_H__
//add
make_helper(add_i2a_b);
make_helper(add_i2rm_b);
make_helper(add_r2rm_b);
make_helper(add_rm2r_b);
//adc
make_helper(adc_i2a_b);
make_helper(adc_i2rm_b);
make_helper(adc_r2rm_b);
make_helper(adc_rm2r_b);
//sbb
make_helper(sbb_i2a_b);
make_helper(sbb_i2rm_b);
make_helper(sbb_r2rm_b);
make_helper(sbb_rm2r_b);
//sub
make_helper(sub_i2a_b);
make_helper(sub_i2rm_b);
make_helper(sub_r2rm_b);
make_helper(sub_rm2r_b);
//inc
make_helper(inc_rm_b);
//dec
make_helper(dec_rm_b);

//add
make_helper(add_i2a_v);
make_helper(add_i2rm_v);
make_helper(add_r2rm_v);
make_helper(add_rm2r_v);
make_helper(add_ib2rm_v);
//adc
make_helper(adc_i2a_v);
make_helper(adc_i2rm_v);
make_helper(adc_r2rm_v);
make_helper(adc_rm2r_v);
make_helper(adc_ib2rm_v);
//sbb
make_helper(sbb_i2a_v);
make_helper(sbb_i2rm_v);
make_helper(sbb_r2rm_v);
make_helper(sbb_rm2r_v);
make_helper(sbb_ib2rm_v);
//sub
make_helper(sub_i2a_v);
make_helper(sub_i2rm_v);
make_helper(sub_r2rm_v);
make_helper(sub_rm2r_v);
make_helper(sub_ib2rm_v);
//inc
make_helper(inc_rm_v);
make_helper(inc_r_v);
//dec
make_helper(dec_rm_v);
make_helper(dec_r_v);

#endif
