#ifndef __or_H__
#define __or_H__
//or
make_helper(or_i2a_b);
make_helper(or_i2rm_b);
make_helper(or_r2rm_b);
make_helper(or_rm2r_b);
//xor
make_helper(xor_i2a_b);
make_helper(xor_i2rm_b);
make_helper(xor_r2rm_b);
make_helper(xor_rm2r_b);
//and
make_helper(and_i2a_b);
make_helper(and_i2rm_b);
make_helper(and_r2rm_b);
make_helper(and_rm2r_b);
//not
make_helper(not_rm_b);
//sal
make_helper(sal_rm_b);
make_helper(sal_rmi_b);
make_helper(sal_cl_b);
//sar
make_helper(sar_rm_b);
make_helper(sar_rmi_b);
make_helper(sar_cl_b);
//shr
make_helper(shr_rm_b);
make_helper(shr_rmi_b);
make_helper(shr_cl_b);

//or
make_helper(or_i2a_v);
make_helper(or_ib2rm_v);
make_helper(or_i2rm_v);
make_helper(or_r2rm_v);
make_helper(or_rm2r_v);
//xor
make_helper(xor_i2a_v);
make_helper(xor_ib2rm_v);
make_helper(xor_i2rm_v);
make_helper(xor_r2rm_v);
make_helper(xor_rm2r_v);
//and
make_helper(and_i2a_v);
make_helper(and_ib2rm_v);
make_helper(and_i2rm_v);
make_helper(and_r2rm_v);
make_helper(and_rm2r_v);
//not
make_helper(not_rm_v);
//sal
make_helper(sal_rm_v);
make_helper(sal_rmi_v);
make_helper(sal_cl_v);
//sar
make_helper(sar_rm_v);
make_helper(sar_rmi_v);
make_helper(sar_cl_v);
//shr
make_helper(shr_rm_v);
make_helper(shr_rmi_v);
make_helper(shr_cl_v);
#endif
